# after i run 
# python manage.py makemigrations bartermonster
# Generated by Django 5.1.7 on 2025-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
# The table is not created at this point yes,  
# after I run command: python manage.py migrate 
# this will make Django create and execute an SQL statement, based on the content of the new file in the /migrations/ folder
# and  will give output:
'''Operations to perform:
  Apply all migrations: admin, auth, contenttypes, members, sessions
Running migrations:
  Applying members.0001_initial... OK

(myworld) C:\..\my_project\bartermonster>'''
# Now I have a "Member" table in my database

# to see database, run: python manage.py sqlmigrate members 0001 
# output:
'''BEGIN;
--
-- Create model Member
--
CREATE TABLE "members_member" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "firstname" varchar(255) NOT NULL, "lastname" varchar(255) NOT NULL);
COMMIT;
